l_russian:
 tank_designer_early_armor_train: "Artillery Train Car" #NT!
 tank_designer_early_armor_train_aa: "Artillery Train Car" #NT!
 tank_nsb_armor_upgrade: "Armor" #NT!
 group_train_combat_support_title: "Train Combat Support" #NT!
  ### EQUIPMENT MODULE CATEGORIES ### 
 EQ_MOD_CAT_train_heavy_artillery_TITLE: "Heavy Artillery" #NT!
 EQ_MOD_CAT_train_aa_TITLE: "Anti-Air Gun" #NT!
 EQ_MOD_CAT_train_machineguns_TITLE: "Heavy Machinegun" #NT!
 EQ_MOD_CAT_train_heavy_aa_TITLE: "Heavy Anti-Air" #NT!
 EQ_MOD_CAT_train_carriage_type_TITLE: "Train Carriage" #NT!
 EQ_MOD_CAT_train_axle_type_TITLE: "Train Axle" #NT!
 EQ_MOD_CAT_train_special_module_TITLE: "Train Support Company" #NT!
  
  ### EQUIPMENT MODULE SLOTS ### 
 EQ_MOD_SLOT_train_main_battery_1_TITLE: "Main Battery" #NT!
 EQ_MOD_SLOT_train_main_battery_2_TITLE: "Main Battery" #NT!
 EQ_MOD_SLOT_train_axle_type_slot_TITLE: "Axle Type" #NT!
 EQ_MOD_SLOT_carriage_type_slot_TITLE: "Carriage Type" #NT!
 EQ_MOD_SLOT_train_secondary_battery_1_TITLE: "Secondary Battery" #NT!
 EQ_MOD_SLOT_train_secondary_battery_2_TITLE: "Secondary Battery" #NT!
 EQ_MOD_SLOT_train_special_module_1_TITLE: "Special Features" #NT!
 EQ_MOD_SLOT_train_special_module_2_TITLE: "Special Features" #NT!
  ### EQUIPMENT MODULES ### 
 train_flat_bed: "Flat Bed" #NT!
 train_open_top: "Open Top" #NT!
 train_enclosed_car: "Enclosed Car" #NT!
 train_1_wheel_axle: "Single-Wheel Axle" #NT!
 train_2_wheel_axle: "Dual-Wheel Axle" #NT!
 train_smoothbore_cannon: "Smoothbore Cannon" #NT!
 train_siege_gun_0: "Early Siege Gun" #NT!
 train_siege_gun_1: "Basic Siege Gun" #NT!
 train_siege_gun_2: "Improved Siege Gun" #NT!
 train_siege_gun_3: "Advanced Siege Gun" #NT!
 train_siege_gun_4: "Late Siege Gun" #NT!
 train_siege_gun_5: "Modern Siege Gun" #NT!
 train_aa_1: "Early Heavy Anti-Air" #NT!
 train_aa_2: "Basic Heavy Anti-Air" #NT!
 train_aa_3: "Improved Heavy Anti-Air" #NT!
 train_aa_4: "Advanced Heavy Anti-Air" #NT!
 train_aa_5: "Late Heavy Anti-Air" #NT!
 train_light_aa_1: "Early Anti-Air" #NT!
 train_light_aa_2: "Basic Anti-Air" #NT!
 train_light_aa_3: "Improved Anti-Air" #NT!
 train_light_aa_4: "Advanced Anti-Air" #NT!
 train_light_aa_5: "Late Anti-Air" #NT!
 train_machinegun_1: "Early Heavy Machine Gun" #NT!
 train_machinegun_2: "Basic Heavy Machine Gun" #NT!
 train_machinegun_2: "Improved Heavy Machine Gun" #NT!
 train_machinegun_3: "Advanced Heavy Machine Gun" #NT!
 train_machinegun_4: "Late Heavy Machine Gun" #NT!
 train_engineer: "Train Engineer Company" #NT!
 train_radio: "Train Signal Company" #NT!
  
  
  
  
  
  
  
  
